<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2022-11-25 17:33:20 --> Severity: error --> Exception: syntax error, unexpected ''username'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' /app/myapp/application/config/database.php 79
ERROR - 2022-11-25 17:35:00 --> Severity: error --> Exception: syntax error, unexpected ''username'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' /app/myapp/application/config/database.php 79
ERROR - 2022-11-25 17:42:54 --> Severity: error --> Exception: syntax error, unexpected ''username'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' /app/myapp/application/config/database.php 79
ERROR - 2022-11-25 17:42:55 --> Severity: error --> Exception: syntax error, unexpected ''username'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' /app/myapp/application/config/database.php 79
ERROR - 2022-11-25 17:42:56 --> Severity: error --> Exception: syntax error, unexpected ''username'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' /app/myapp/application/config/database.php 79
ERROR - 2022-11-25 17:43:14 --> Query error: Table 'bitnami_myapp.ci_sessions' doesn't exist - Invalid query: SELECT `data`
FROM `ci_sessions`
WHERE `id` = 'co2cl7fv2lapa93smtjcgq4tlsfep290'
ERROR - 2022-11-25 17:43:14 --> Severity: Warning --> session_write_close(): Cannot call session save handler in a recursive manner Unknown 0
ERROR - 2022-11-25 17:43:14 --> Severity: Warning --> session_write_close(): Failed to write session data using user defined save handler. (session.save_path: ) Unknown 0
ERROR - 2022-11-25 21:05:12 --> Query error: Table 'bitnami_myapp.ci_sessions' doesn't exist - Invalid query: SELECT `data`
FROM `ci_sessions`
WHERE `id` = '9pvlui8ildvjdeuvokpbcb0bbudaa1us'
ERROR - 2022-11-25 21:05:12 --> Severity: Warning --> session_write_close(): Cannot call session save handler in a recursive manner Unknown 0
ERROR - 2022-11-25 21:05:12 --> Severity: Warning --> session_write_close(): Failed to write session data using user defined save handler. (session.save_path: ) Unknown 0
ERROR - 2022-11-25 22:13:34 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused /app/myapp/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-11-25 22:13:34 --> Unable to connect to the database
ERROR - 2022-11-25 22:13:39 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused /app/myapp/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-11-25 22:13:39 --> Unable to connect to the database
ERROR - 2022-11-25 22:13:48 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused /app/myapp/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-11-25 22:13:48 --> Unable to connect to the database
ERROR - 2022-11-25 22:13:55 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused /app/myapp/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-11-25 22:13:55 --> Unable to connect to the database
ERROR - 2022-11-25 22:14:08 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused /app/myapp/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-11-25 22:14:08 --> Unable to connect to the database
ERROR - 2022-11-25 22:26:41 --> Severity: Warning --> mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known /app/myapp/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-11-25 22:26:41 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known /app/myapp/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-11-25 22:26:41 --> Unable to connect to the database
ERROR - 2022-11-25 22:31:19 --> Severity: Warning --> mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution /app/myapp/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-11-25 22:31:19 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution /app/myapp/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-11-25 22:31:19 --> Unable to connect to the database
ERROR - 2022-11-25 22:32:40 --> Severity: Warning --> mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution /app/myapp/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-11-25 22:32:40 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution /app/myapp/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-11-25 22:32:40 --> Unable to connect to the database
ERROR - 2022-11-25 22:38:37 --> Severity: Warning --> mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known /app/myapp/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-11-25 22:38:37 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known /app/myapp/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-11-25 22:38:37 --> Unable to connect to the database
ERROR - 2022-11-25 22:40:04 --> Severity: Warning --> mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution /app/myapp/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-11-25 22:40:04 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution /app/myapp/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-11-25 22:40:04 --> Unable to connect to the database
ERROR - 2022-11-25 22:42:50 --> Severity: Warning --> mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known /app/myapp/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-11-25 22:42:50 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known /app/myapp/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-11-25 22:42:50 --> Unable to connect to the database
ERROR - 2022-11-25 22:45:49 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused /app/myapp/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-11-25 22:45:49 --> Unable to connect to the database
ERROR - 2022-11-25 22:45:53 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused /app/myapp/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-11-25 22:45:53 --> Unable to connect to the database
ERROR - 2022-11-25 22:48:43 --> Query error: Table 'bitnami_myapp.ci_sessions' doesn't exist - Invalid query: SELECT 1
FROM `ci_sessions`
WHERE `id` = 'c1ie7c62s0ohv8m3b2bgskpbah2v23kc'
ERROR - 2022-11-25 22:59:16 --> Query error: Unknown column 'fecha' in 'where clause' - Invalid query: SELECT `vw_reporte_pm`.*, j35389aaf.lote AS s35389aaf, `vw_reporte_pm`.lote AS 'vw_reporte_pm.lote'
FROM `vw_reporte_pm`
LEFT JOIN `z_lote` as `j35389aaf` ON `j35389aaf`.`id` = `vw_reporte_pm`.`lote`
WHERE `fecha` = '1969-12-31'
